FROM ubuntu:22.04

# renovate: datasource=github-releases depName=ikefarah/yq versioning=semver
ARG YQ_VERSION="v4.30.6"
ARG YQ_CHECKSUM="2aabdd748d301fc2286ea9f73eb20477b4ce173fbf072e0102fff1fcbed05985"