
name: CI
on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build buf
      - run: docker build containerd
      - run: docker build firecracker
      - run: docker build gosu
